name: jaspr_markdown_example
description: A new jaspr project.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.20.0
  jaspr_markdown:
    path: ../

dev_dependencies:
  build_runner: ^2.5.4
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.20.0
  lints: ^6.0.0

jaspr:
  mode: static
