name: jaspr_markdown_example
description: A new jaspr project.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.21.3
  jaspr_markdown:
    path: ../

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.3+1
  jaspr_builder: ^0.21.2
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static
